### ISSUE TITLE
Docker容器中2531端口无法启动，2532端口显示404

### ISSUE THREAD

**Issue by sylearn** [Devo919/Gewechat#71]
因为微信二维码显示您加好友过于频繁无法进群交流，因此把问题写到这里
docker-compose.yml如下：
```yaml
version: '3'

services:
  gewe:
    image: registry.cn-hangzhou.aliyuncs.com/gewe/gewe:latest
    container_name: gewe
    privileged: true # 允许容器访问主机网络
    restart: always
    ports:
      - "2531:2531"  # API服务端口
      - "2532:2532"  # 文件下载服务端口
    volumes:
      - ./temp:/root/temp  # 挂载临时文件目录
    command: /usr/sbin/init
    tty: true
    stdin_open: true
    user: root  # 使用root用户运行
    # 确保容器在 down 后被删除
    labels:
      - "com.docker.compose.remove=true" 
   ```
日志显示：
![image](https://github.com/user-attachments/assets/e15ce617-8645-4204-b529-e024a148dac4)
进入容器后检查端口状态显示：
![image](https://github.com/user-attachments/assets/d8fd1e52-2262-4c01-a0ec-5970fd4a3c00)
发现并没有开启2531的API端口。
因此：
访问2531端口：502
访问2542端口：404
