### ISSUE TITLE
CentOS 9 stream 不可用。

### ISSUE THREAD

**Issue by pigwan** [Devo919/Gewechat#97]

**Comment by pigwan** [comment]
@Devo919 已经安排了一个centos7设备。给大家个提示，避免走弯路。
感谢大佬。

**Comment by ChanLicher** [comment]
你是用在AstrBot项目里的吗？我的CentOS9是可以正常使用的

**Comment by pigwan** [comment]
> 你是用在AstrBot项目里的吗？我的CentOS9是可以正常使用的

本来我是在自己的家里的服务器，用了frp，装的东西也挺多了，我本来以为是我frp或者装东西太多，可能哪些配置冲突了。
然后我就在阿里云新建了一个centos7的实例发现正常，再新建了一个centos9的实例，就出现和我家里服务器一样的情况了。

**Comment by ChanLicher** [comment]
> > 你是用在AstrBot项目里的吗？我的CentOS9是可以正常使用的
> 
> 本来我是在自己的家里的服务器，用了frp，装的东西也挺多了，我本来以为是我frp或者装东西太多，可能哪些配置冲突了。 然后我就在阿里云新建了一个centos7的实例发现正常，再新建了一个centos9的实例，就出现和我家里服务器一样的情况了。

我也试过了不少系统，都是用docker，遇到的主要问题还是两个容器的通信问题。我是没想到直接用host模式都有可能通不了。在AstrBot的issue里。有人提到使用docker创建一个网络，然后在同一个网络里的容器只要用services的名称代替ip就可以通信（比如我下面复制的compose文件里的gewechat）。

我先是部署在群晖，然后是CentOS7的云服务器（这个倒是可以用，但我觉得把数据放在本地好一点），最后在PVE里新建了一个CentOS9的LXC容器运行。

我还是在这个CentOS9里用docker部署的，而且我找到了一个别人Build的很小的gewechat镜像，以下是我的docker compose，如果你觉得有用的话，可以试试看。

```
services:
  gewechat:
    image: wuhuan123/gewechat:latest
    container_name: Gewechat
    restart: always
    privileged: true
    tty: true
    stdin_open: true
    networks:
      - astrbot_network
    ports:
      - "2531:2531"
      - "2532:2532"
    volumes:
      - /path/to/gewechat:/root/temp
    healthcheck:
      test: ["CMD", "nc", "-zv", "127.0.0.1", "2531"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
  
  astrbot:
    image: soulter/astrbot:latest
    container_name: Astrbot
    restart: always
    networks:
      - astrbot_network
    ports:
      - "6180-6200:6180-6200"
      - "11451:11451"
    depends_on:
      gewechat:
        condition: service_healthy
    environment:
      - TZ=US/Eastern
    volumes:
      - /path/to/astrbot:/AstrBot/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  astrbot_network:
    name: astrbot_network
    driver: bridge
```
